# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddb4d9d01ce12269f9014c43b5ca9378bef60348861118c943cdd948b5ae2afd96978f97ba8bae1ddd82c52325074c60298c8d48a271b1979fb237002be078cd

test:
  secret_key_base: 20e05b7256e389d922e0b974d8e4c7dbc574abfaea27344f807403174b10b340c20f2c50000a78f2f16e23a00de9c4c16abf8c2e5005d9369e29695120e82a3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
